logLevel: info

image:
  #definir tag somente para analise
  #tag: "1.9.8-debug"
  pullPolicy: IfNotPresent

securityContext:
  readOnlyRootFilesystem: true

service:
  annotations:
    prometheus.io/path: "/api/v1/metrics/prometheus"
    prometheus.io/port: "2020"
    prometheus.io/scrape: "true"

serviceMonitor:
  enabled: true
  namespace: sre-monitoring
  interval: 10s
  scrapeTimeout: 10s
  selector:
    release: prom

tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Exists
  - effect: NoExecute
    operator: Exists
  - effect: NoSchedule
    operator: Exists
  

podAnnotations:
  fluentbit.io/exclude: "true"

config:
  service: |
    [SERVICE]
        Daemon Off
        Flush 1
        Log_Level info
        Parsers_File custom_parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port 2020
        Health_Check On
        storage.path /var/log/flb-storage/
        storage.backlog.mem_limit 20M
  inputs: |
    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        Parser docker_custom
        Mem_Buf_Limit 50MB
        DB /var/log/flb-storage/flb_container.db
        storage.type  filesystem
        Tag container.*
  filters: |
    [FILTER]
        Name kubernetes
        Match services.*
        Merge_Log Off
        Keep_Log Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On
  outputs: |
    [OUTPUT]
        Name   loki
        Host   loki-core.com
        Port   80
        Match  *
        labels job=$TAG
  customParsers: |
    [PARSER]
        Name docker_custom
        Format json
        Time_Keep On
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L